app/orders/__init__.py
from flask import Blueprint

orders_bp = Blueprint('orders', __name__,
                      template_folder='templates', url_prefix=('/pedidos'))

app/orders/routes.py
from flask import render_template, g, request, redirect, url_for, abort

from app.orders import orders_bp
from app.db import db, cursor, time_zone

from datetime import datetime

hoy = datetime.now()
meses = ('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
         'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre')
numero_mes = int(hoy.strftime('%m'))
mes_actual = numero_mes - 1
fecha = hoy.strftime(
    '%d de {} del %Y').format(meses[mes_actual])


@orders_bp.route('/print/<int:id>', methods=['GET', 'POST'])
def print_ticket(id):

    query = ('SELECT * FROM productos WHERE id = %s')
    cursor.execute(query, (id,))

    data = cursor.fetchone()

    if data is not None:

        client = data[1]
        product = data[2]
        size = data[3]
        quantity = data[4]
        date = data[5]
        date_n = date.strftime('%d de {} del %Y').format(meses[mes_actual])
        hour = data[6]
        description = data[7]
        amount = data[8]
        rest = data[9]
        total = data[10]

    return render_template('print_opro.html', cliente=client, producto=product, tamaño=size, cantidad=quantity, fecha=date_n, hora=hour, descripcion=description, anticipo=amount, resta=rest, total=total)


@orders_bp.route('/pedidos_produccion', methods=['GET', 'POST'])
def view_orders_production():

    time_zone
    cursor.execute(
        'SELECT DATE_FORMAT(fecha,"%d de %M del %Y"),cliente,producto,tamaño,cantidad,descripcion,id FROM productos ORDER BY fecha')

    pedidos = cursor.fetchall()

    return render_template('order_list.html', pedidos=pedidos)


@orders_bp.route('/nuevo_pedido', methods=['GET', 'POST'])
def new_orders():
    if request.method == 'POST':
        cliente = request.form['cliente']
        producto = request.form['producto']
        tamaño = request.form['tamaño']
        cantidad = request.form['cantidad']
        fecha = request.form['fecha']
        hora = request.form['hora']
        descripcion = request.form['descripcion']
        anticipo = request.form['anticipo']
        resta = request.form['resta']
        total = request.form['total']

        cursor.execute(
            'INSERT INTO productos (cliente,producto,tamaño,cantidad,fecha,hora,descripcion,anticipo,resta,total)'
            'VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)', (cliente, producto, tamaño, cantidad, fecha, hora, descripcion, anticipo, resta, total))

        db.commit()

        return redirect(url_for('orders.view_orders_production'))

    return render_template('new_orders.html')

app/orders/templates/base_orders.html
<div>{{ fecha }}</div>

app/orders/templates/new_orders.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Nuevo Pedido{% endblock %}
<!--  -->
{% block content %} {% include 'base_orders.html' %}
<h2>Ingresar Pedido</h2>
<span
  ><a href="{{ url_for('orders.view_orders_production') }}">Pedidos</a></span
>
<section class="new_orders">
  <form action="nuevo_pedido" method="POST">
    <label>Cliente</label>
    <input type="text" name="cliente" />
    <label>Producto</label>
    <select name="producto" id="product" onchange="calculate_total()">
      <option value="Baileys">Baileys</option>
      <option value="Cheesecake">Cheesecake</option>
      <option value="Chocoflan">Chocoflan</option>
      <option value="Choconuez">Choconuez</option>
      <option value="Flan napolitano">Flan napolitano</option>
      <option value="Kahlua">Kahlua</option>
      <option value="Manjar">Manjar</option>
      <option value="Mantequilla">Mantequilla</option>
      <option value="Marmoleado">Marmoleado</option>
      <option value="Nutella">Nutella</option>
      <option value="Oreo">Oreo</option>
      <option value="Panque">Panque</option>
      <option value="Piña coco">Piña coco</option>
      <option value="Rompope">Rompope</option>
      <option value="Tarta de fresa">Tarta de fresa</option>
      <option value="Torta de pan">Torta de pan</option>
      <option value="Torta de pan con domo">Torta de pan con domo</option>
      <option value="Tropical">Tropical</option>
    </select>
    <label>Tamaño</label>
    <select name="tamaño" id="size" onchange="calculate_total()">
      <option value="1/4 kg">1/4 kg</option>
      <option value="1/2 kg">1/2 kg</option>
      <option value="3/4 kg">3/4 kg</option>
      <option value="1 kg">1kg</option>
      <option value="1 1/4 kg">1 1/4 kg</option>
      <option value="1 1/2 kg">1 1/2 kg</option>
      <option value="1 3/4 kg">1 3/4 kg</option>
      <option value="2 kg">2 kg</option>
    </select>
    <label>Cantidad</label>
    <input
      type="number"
      name="cantidad"
      id="quantity"
      value="1"
      onchange="calculate_total()"
    />
    <label>Fecha</label>
    <!-- <input type="text" name="fecha" /> -->
    <input type="date" name="fecha" />
    <label>Hora</label>
    <select name="hora">
      <option value="08:00 Hrs">08:00 Hrs</option>
      <option value="09:00 Hrs">09:00 Hrs</option>
      <option value="10:00 Hrs">10:00 Hrs</option>
      <option value="11:00 Hrs">11:00 Hrs</option>
      <option value="12:00 Hrs">12:00 Hrs</option>
      <option value="13:00 Hrs">13:00 Hrs</option>
      <option value="14:00 Hrs">14:00 Hrs</option>
      <option value="15:00 Hrs">15:00 Hrs</option>
      <option value="16:00 Hrs">16:00 Hrs</option>
      <option value="17:00 Hrs">17:00 Hrs</option>
      <option value="18:00 Hrs">18:00 Hrs</option>
      <option value="19:00 Hrs">19:00 Hrs</option>
      <option value="20:00 Hrs">20:00 Hrs</option>
    </select>
    <label>Descripción</label>
    <textarea name="descripcion" rows="10" cols="50"></textarea>
    <label>Anticipo</label>
    <input
      type="text"
      name="anticipo"
      id="advance"
      onchange="calculate_total()"
    />
    <label>Resta</label>
    <input type="text" name="resta" id="rest" readonly />
    <label>Total</label>
    <input type="text" name="total" id="total" value="" readonly />
    <input type="submit" value="Ingresar" />
  </form>
</section>
{% endblock %}

app/orders/templates/order_list.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Pedidos{% endblock %}
<!--  -->
{% block content %}
<section class="orders">
  <h2>Pedidos</h2>
  <div class="link">
    <a href="{{ url_for('orders.new_orders') }}">Nuevo pedido</a>
  </div>
  {% for pedido in pedidos %}
  <div class="order">
    <div class="order-data">
      <div class="order-data__client">
        {{ pedido.1 }} |
        <strong>{{ pedido.4 }} {{ pedido.2 }} de {{ pedido.3 }}</strong>
      </div>
      <a
        class="order-print"
        href="{{ url_for('orders.print_ticket',id=pedido.6) }}"
        >Imprimir</a
      >
    </div>
    <div class="order-line"></div>
    <div class="order-description">{{ pedido.5 }}</div>
  </div>
  {% endfor %}
</section>
{% endblock %}

app/orders/templates/orders_pro.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Pedidos{% endblock %}
<!--  -->
{% block content %}
<h2>Pedidos</h2>
<span><a href="{{ url_for('orders.new_orders') }}">Ingresar pedido</a></span>
<section class="orders">
  <table>
    <thead>
      <tr>
        <th>FECHA</th>
        <th>CLIENTE</th>
        <th>PRODUCTO</th>
        <th>TAM</th>
        <th>C</th>
        <th>DESCRIPCIÓN</th>
        <th>OPCIONES</th>
      </tr>
    </thead>
    <tbody>
      {% for pedido in pedidos %}
      <tr>
        <td>{{ pedido.0 }}</td>
        <td>{{ pedido.1 }}</td>
        <td>{{ pedido.2 }}</td>
        <td>{{ pedido.3 }}</td>
        <td>{{ pedido.4 }}</td>
        <td>{{ pedido.5 }}</td>
        <td>
          <a href="{{ url_for('orders.print_ticket',id=pedido.6) }}"
            >Imprimir</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
{% endblock %}

app/orders/templates/print_opro.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Print{% endblock %}
<!--  -->
{% block content %}
<section class="print-container">
  <div class="print-container__date">
    <p><b>D'CHELIS | CENTRAL</b></p>
    <p>{{ fecha }} / {{ hora }}</p>
    <p>{{ cliente }}</p>
  </div>
  <div class="space"></div>
  <div class="print-container__data">
    <p>{{ cantidad }} {{ producto }}</p>
    <p><b>TAMAÑO:</b> {{ tamaño }}</p>
    <p><b>DESCRIPCIÓN:</b> {{ descripcion }}</p>
  </div>
  <div class="space"></div>
</section>

<script>
  function load() {
    return new Promise((resolve) => {
      setTimeout(() => {
        window.location.href = "{{ url_for('orders.view_orders_production') }}";
      }, 1000);
    });
  }

  async function print_ticket() {
    window.print();
    await load();
  }

  print_ticket();
</script>

{% endblock %}